# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dbos_pb2 as dbos__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dbos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBOSStub(object):
    """DBOS Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/dbos.DBOS/RegisterAgent',
                request_serializer=dbos__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=dbos__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/dbos.DBOS/GetAgent',
                request_serializer=dbos__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=dbos__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/dbos.DBOS/ListAgents',
                request_serializer=dbos__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=dbos__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.SetModuleState = channel.unary_unary(
                '/dbos.DBOS/SetModuleState',
                request_serializer=dbos__pb2.SetModuleStateRequest.SerializeToString,
                response_deserializer=dbos__pb2.SetModuleStateResponse.FromString,
                _registered_method=True)
        self.GetModuleState = channel.unary_unary(
                '/dbos.DBOS/GetModuleState',
                request_serializer=dbos__pb2.GetModuleStateRequest.SerializeToString,
                response_deserializer=dbos__pb2.GetModuleStateResponse.FromString,
                _registered_method=True)
        self.ListModuleStates = channel.unary_unary(
                '/dbos.DBOS/ListModuleStates',
                request_serializer=dbos__pb2.ListModuleStatesRequest.SerializeToString,
                response_deserializer=dbos__pb2.ListModuleStatesResponse.FromString,
                _registered_method=True)
        self.StoreResult = channel.unary_unary(
                '/dbos.DBOS/StoreResult',
                request_serializer=dbos__pb2.StoreResultRequest.SerializeToString,
                response_deserializer=dbos__pb2.StoreResultResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/dbos.DBOS/GetResult',
                request_serializer=dbos__pb2.GetResultRequest.SerializeToString,
                response_deserializer=dbos__pb2.GetResultResponse.FromString,
                _registered_method=True)
        self.ListResults = channel.unary_unary(
                '/dbos.DBOS/ListResults',
                request_serializer=dbos__pb2.ListResultsRequest.SerializeToString,
                response_deserializer=dbos__pb2.ListResultsResponse.FromString,
                _registered_method=True)
        self.ScheduleTask = channel.unary_unary(
                '/dbos.DBOS/ScheduleTask',
                request_serializer=dbos__pb2.ScheduleTaskRequest.SerializeToString,
                response_deserializer=dbos__pb2.ScheduleTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/dbos.DBOS/GetTask',
                request_serializer=dbos__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=dbos__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListDueTasks = channel.unary_unary(
                '/dbos.DBOS/ListDueTasks',
                request_serializer=dbos__pb2.ListDueTasksRequest.SerializeToString,
                response_deserializer=dbos__pb2.ListDueTasksResponse.FromString,
                _registered_method=True)
        self.AckTask = channel.unary_unary(
                '/dbos.DBOS/AckTask',
                request_serializer=dbos__pb2.AckTaskRequest.SerializeToString,
                response_deserializer=dbos__pb2.AckTaskResponse.FromString,
                _registered_method=True)
        self.NackTask = channel.unary_unary(
                '/dbos.DBOS/NackTask',
                request_serializer=dbos__pb2.NackTaskRequest.SerializeToString,
                response_deserializer=dbos__pb2.NackTaskResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/dbos.DBOS/GetEvents',
                request_serializer=dbos__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=dbos__pb2.GetEventsResponse.FromString,
                _registered_method=True)


class DBOSServicer(object):
    """DBOS Service Definition
    """

    def RegisterAgent(self, request, context):
        """Agent Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModuleState(self, request, context):
        """Module State Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModuleStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreResult(self, request, context):
        """Measurement Results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleTask(self, request, context):
        """Task Scheduling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDueTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NackTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Event Logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBOSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=dbos__pb2.RegisterAgentRequest.FromString,
                    response_serializer=dbos__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=dbos__pb2.GetAgentRequest.FromString,
                    response_serializer=dbos__pb2.GetAgentResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=dbos__pb2.ListAgentsRequest.FromString,
                    response_serializer=dbos__pb2.ListAgentsResponse.SerializeToString,
            ),
            'SetModuleState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModuleState,
                    request_deserializer=dbos__pb2.SetModuleStateRequest.FromString,
                    response_serializer=dbos__pb2.SetModuleStateResponse.SerializeToString,
            ),
            'GetModuleState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleState,
                    request_deserializer=dbos__pb2.GetModuleStateRequest.FromString,
                    response_serializer=dbos__pb2.GetModuleStateResponse.SerializeToString,
            ),
            'ListModuleStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModuleStates,
                    request_deserializer=dbos__pb2.ListModuleStatesRequest.FromString,
                    response_serializer=dbos__pb2.ListModuleStatesResponse.SerializeToString,
            ),
            'StoreResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreResult,
                    request_deserializer=dbos__pb2.StoreResultRequest.FromString,
                    response_serializer=dbos__pb2.StoreResultResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=dbos__pb2.GetResultRequest.FromString,
                    response_serializer=dbos__pb2.GetResultResponse.SerializeToString,
            ),
            'ListResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResults,
                    request_deserializer=dbos__pb2.ListResultsRequest.FromString,
                    response_serializer=dbos__pb2.ListResultsResponse.SerializeToString,
            ),
            'ScheduleTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleTask,
                    request_deserializer=dbos__pb2.ScheduleTaskRequest.FromString,
                    response_serializer=dbos__pb2.ScheduleTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=dbos__pb2.GetTaskRequest.FromString,
                    response_serializer=dbos__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListDueTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDueTasks,
                    request_deserializer=dbos__pb2.ListDueTasksRequest.FromString,
                    response_serializer=dbos__pb2.ListDueTasksResponse.SerializeToString,
            ),
            'AckTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AckTask,
                    request_deserializer=dbos__pb2.AckTaskRequest.FromString,
                    response_serializer=dbos__pb2.AckTaskResponse.SerializeToString,
            ),
            'NackTask': grpc.unary_unary_rpc_method_handler(
                    servicer.NackTask,
                    request_deserializer=dbos__pb2.NackTaskRequest.FromString,
                    response_serializer=dbos__pb2.NackTaskResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=dbos__pb2.GetEventsRequest.FromString,
                    response_serializer=dbos__pb2.GetEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbos.DBOS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbos.DBOS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DBOS(object):
    """DBOS Service Definition
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/RegisterAgent',
            dbos__pb2.RegisterAgentRequest.SerializeToString,
            dbos__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/GetAgent',
            dbos__pb2.GetAgentRequest.SerializeToString,
            dbos__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/ListAgents',
            dbos__pb2.ListAgentsRequest.SerializeToString,
            dbos__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModuleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/SetModuleState',
            dbos__pb2.SetModuleStateRequest.SerializeToString,
            dbos__pb2.SetModuleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModuleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/GetModuleState',
            dbos__pb2.GetModuleStateRequest.SerializeToString,
            dbos__pb2.GetModuleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModuleStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/ListModuleStates',
            dbos__pb2.ListModuleStatesRequest.SerializeToString,
            dbos__pb2.ListModuleStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/StoreResult',
            dbos__pb2.StoreResultRequest.SerializeToString,
            dbos__pb2.StoreResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/GetResult',
            dbos__pb2.GetResultRequest.SerializeToString,
            dbos__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/ListResults',
            dbos__pb2.ListResultsRequest.SerializeToString,
            dbos__pb2.ListResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/ScheduleTask',
            dbos__pb2.ScheduleTaskRequest.SerializeToString,
            dbos__pb2.ScheduleTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/GetTask',
            dbos__pb2.GetTaskRequest.SerializeToString,
            dbos__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDueTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/ListDueTasks',
            dbos__pb2.ListDueTasksRequest.SerializeToString,
            dbos__pb2.ListDueTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/AckTask',
            dbos__pb2.AckTaskRequest.SerializeToString,
            dbos__pb2.AckTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NackTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/NackTask',
            dbos__pb2.NackTaskRequest.SerializeToString,
            dbos__pb2.NackTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbos.DBOS/GetEvents',
            dbos__pb2.GetEventsRequest.SerializeToString,
            dbos__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
