// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/dbos.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBOS_RegisterAgent_FullMethodName    = "/dbos.DBOS/RegisterAgent"
	DBOS_GetAgent_FullMethodName         = "/dbos.DBOS/GetAgent"
	DBOS_ListAgents_FullMethodName       = "/dbos.DBOS/ListAgents"
	DBOS_SetModuleState_FullMethodName   = "/dbos.DBOS/SetModuleState"
	DBOS_GetModuleState_FullMethodName   = "/dbos.DBOS/GetModuleState"
	DBOS_ListModuleStates_FullMethodName = "/dbos.DBOS/ListModuleStates"
	DBOS_StoreResult_FullMethodName      = "/dbos.DBOS/StoreResult"
	DBOS_GetResult_FullMethodName        = "/dbos.DBOS/GetResult"
	DBOS_ListResults_FullMethodName      = "/dbos.DBOS/ListResults"
	DBOS_ScheduleTask_FullMethodName     = "/dbos.DBOS/ScheduleTask"
	DBOS_GetTask_FullMethodName          = "/dbos.DBOS/GetTask"
	DBOS_ListDueTasks_FullMethodName     = "/dbos.DBOS/ListDueTasks"
	DBOS_AckTask_FullMethodName          = "/dbos.DBOS/AckTask"
	DBOS_NackTask_FullMethodName         = "/dbos.DBOS/NackTask"
	DBOS_GetEvents_FullMethodName        = "/dbos.DBOS/GetEvents"
)

// DBOSClient is the client API for DBOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DBOS Service Definition
type DBOSClient interface {
	// Agent Management
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// Module State Management
	SetModuleState(ctx context.Context, in *SetModuleStateRequest, opts ...grpc.CallOption) (*SetModuleStateResponse, error)
	GetModuleState(ctx context.Context, in *GetModuleStateRequest, opts ...grpc.CallOption) (*GetModuleStateResponse, error)
	ListModuleStates(ctx context.Context, in *ListModuleStatesRequest, opts ...grpc.CallOption) (*ListModuleStatesResponse, error)
	// Measurement Results
	StoreResult(ctx context.Context, in *StoreResultRequest, opts ...grpc.CallOption) (*StoreResultResponse, error)
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	ListResults(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*ListResultsResponse, error)
	// Task Scheduling
	ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListDueTasks(ctx context.Context, in *ListDueTasksRequest, opts ...grpc.CallOption) (*ListDueTasksResponse, error)
	AckTask(ctx context.Context, in *AckTaskRequest, opts ...grpc.CallOption) (*AckTaskResponse, error)
	NackTask(ctx context.Context, in *NackTaskRequest, opts ...grpc.CallOption) (*NackTaskResponse, error)
	// Event Logging
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type dBOSClient struct {
	cc grpc.ClientConnInterface
}

func NewDBOSClient(cc grpc.ClientConnInterface) DBOSClient {
	return &dBOSClient{cc}
}

func (c *dBOSClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, DBOS_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, DBOS_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, DBOS_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) SetModuleState(ctx context.Context, in *SetModuleStateRequest, opts ...grpc.CallOption) (*SetModuleStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetModuleStateResponse)
	err := c.cc.Invoke(ctx, DBOS_SetModuleState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) GetModuleState(ctx context.Context, in *GetModuleStateRequest, opts ...grpc.CallOption) (*GetModuleStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleStateResponse)
	err := c.cc.Invoke(ctx, DBOS_GetModuleState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) ListModuleStates(ctx context.Context, in *ListModuleStatesRequest, opts ...grpc.CallOption) (*ListModuleStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModuleStatesResponse)
	err := c.cc.Invoke(ctx, DBOS_ListModuleStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) StoreResult(ctx context.Context, in *StoreResultRequest, opts ...grpc.CallOption) (*StoreResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResultResponse)
	err := c.cc.Invoke(ctx, DBOS_StoreResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, DBOS_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) ListResults(ctx context.Context, in *ListResultsRequest, opts ...grpc.CallOption) (*ListResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResultsResponse)
	err := c.cc.Invoke(ctx, DBOS_ListResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) ScheduleTask(ctx context.Context, in *ScheduleTaskRequest, opts ...grpc.CallOption) (*ScheduleTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTaskResponse)
	err := c.cc.Invoke(ctx, DBOS_ScheduleTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, DBOS_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) ListDueTasks(ctx context.Context, in *ListDueTasksRequest, opts ...grpc.CallOption) (*ListDueTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDueTasksResponse)
	err := c.cc.Invoke(ctx, DBOS_ListDueTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) AckTask(ctx context.Context, in *AckTaskRequest, opts ...grpc.CallOption) (*AckTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckTaskResponse)
	err := c.cc.Invoke(ctx, DBOS_AckTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) NackTask(ctx context.Context, in *NackTaskRequest, opts ...grpc.CallOption) (*NackTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackTaskResponse)
	err := c.cc.Invoke(ctx, DBOS_NackTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBOSClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, DBOS_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBOSServer is the server API for DBOS service.
// All implementations must embed UnimplementedDBOSServer
// for forward compatibility.
//
// DBOS Service Definition
type DBOSServer interface {
	// Agent Management
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// Module State Management
	SetModuleState(context.Context, *SetModuleStateRequest) (*SetModuleStateResponse, error)
	GetModuleState(context.Context, *GetModuleStateRequest) (*GetModuleStateResponse, error)
	ListModuleStates(context.Context, *ListModuleStatesRequest) (*ListModuleStatesResponse, error)
	// Measurement Results
	StoreResult(context.Context, *StoreResultRequest) (*StoreResultResponse, error)
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	ListResults(context.Context, *ListResultsRequest) (*ListResultsResponse, error)
	// Task Scheduling
	ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListDueTasks(context.Context, *ListDueTasksRequest) (*ListDueTasksResponse, error)
	AckTask(context.Context, *AckTaskRequest) (*AckTaskResponse, error)
	NackTask(context.Context, *NackTaskRequest) (*NackTaskResponse, error)
	// Event Logging
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	mustEmbedUnimplementedDBOSServer()
}

// UnimplementedDBOSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBOSServer struct{}

func (UnimplementedDBOSServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedDBOSServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedDBOSServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedDBOSServer) SetModuleState(context.Context, *SetModuleStateRequest) (*SetModuleStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetModuleState not implemented")
}
func (UnimplementedDBOSServer) GetModuleState(context.Context, *GetModuleStateRequest) (*GetModuleStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModuleState not implemented")
}
func (UnimplementedDBOSServer) ListModuleStates(context.Context, *ListModuleStatesRequest) (*ListModuleStatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModuleStates not implemented")
}
func (UnimplementedDBOSServer) StoreResult(context.Context, *StoreResultRequest) (*StoreResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreResult not implemented")
}
func (UnimplementedDBOSServer) GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedDBOSServer) ListResults(context.Context, *ListResultsRequest) (*ListResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResults not implemented")
}
func (UnimplementedDBOSServer) ScheduleTask(context.Context, *ScheduleTaskRequest) (*ScheduleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleTask not implemented")
}
func (UnimplementedDBOSServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedDBOSServer) ListDueTasks(context.Context, *ListDueTasksRequest) (*ListDueTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDueTasks not implemented")
}
func (UnimplementedDBOSServer) AckTask(context.Context, *AckTaskRequest) (*AckTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckTask not implemented")
}
func (UnimplementedDBOSServer) NackTask(context.Context, *NackTaskRequest) (*NackTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NackTask not implemented")
}
func (UnimplementedDBOSServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedDBOSServer) mustEmbedUnimplementedDBOSServer() {}
func (UnimplementedDBOSServer) testEmbeddedByValue()              {}

// UnsafeDBOSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBOSServer will
// result in compilation errors.
type UnsafeDBOSServer interface {
	mustEmbedUnimplementedDBOSServer()
}

func RegisterDBOSServer(s grpc.ServiceRegistrar, srv DBOSServer) {
	// If the following call pancis, it indicates UnimplementedDBOSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBOS_ServiceDesc, srv)
}

func _DBOS_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_SetModuleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModuleStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).SetModuleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_SetModuleState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).SetModuleState(ctx, req.(*SetModuleStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_GetModuleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).GetModuleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_GetModuleState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).GetModuleState(ctx, req.(*GetModuleStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_ListModuleStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModuleStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).ListModuleStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_ListModuleStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).ListModuleStates(ctx, req.(*ListModuleStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_StoreResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).StoreResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_StoreResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).StoreResult(ctx, req.(*StoreResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_ListResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).ListResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_ListResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).ListResults(ctx, req.(*ListResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_ScheduleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).ScheduleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_ScheduleTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).ScheduleTask(ctx, req.(*ScheduleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_ListDueTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDueTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).ListDueTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_ListDueTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).ListDueTasks(ctx, req.(*ListDueTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_AckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).AckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_AckTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).AckTask(ctx, req.(*AckTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_NackTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).NackTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_NackTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).NackTask(ctx, req.(*NackTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBOS_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBOSServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBOS_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBOSServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBOS_ServiceDesc is the grpc.ServiceDesc for DBOS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBOS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbos.DBOS",
	HandlerType: (*DBOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _DBOS_RegisterAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _DBOS_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _DBOS_ListAgents_Handler,
		},
		{
			MethodName: "SetModuleState",
			Handler:    _DBOS_SetModuleState_Handler,
		},
		{
			MethodName: "GetModuleState",
			Handler:    _DBOS_GetModuleState_Handler,
		},
		{
			MethodName: "ListModuleStates",
			Handler:    _DBOS_ListModuleStates_Handler,
		},
		{
			MethodName: "StoreResult",
			Handler:    _DBOS_StoreResult_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _DBOS_GetResult_Handler,
		},
		{
			MethodName: "ListResults",
			Handler:    _DBOS_ListResults_Handler,
		},
		{
			MethodName: "ScheduleTask",
			Handler:    _DBOS_ScheduleTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _DBOS_GetTask_Handler,
		},
		{
			MethodName: "ListDueTasks",
			Handler:    _DBOS_ListDueTasks_Handler,
		},
		{
			MethodName: "AckTask",
			Handler:    _DBOS_AckTask_Handler,
		},
		{
			MethodName: "NackTask",
			Handler:    _DBOS_NackTask_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _DBOS_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/dbos.proto",
}
