// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: api/dbos.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent represents a measurement agent in the system
type Agent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Alive           bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeen        int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	FirstSeen       int64                  `protobuf:"varint,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	Config          map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalHeartbeats int32                  `protobuf:"varint,7,opt,name=total_heartbeats,json=totalHeartbeats,proto3" json:"total_heartbeats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_api_dbos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Agent) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Agent) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *Agent) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Agent) GetTotalHeartbeats() int32 {
	if x != nil {
		return x.TotalHeartbeats
	}
	return 0
}

// ModuleState represents the state of a module execution
type ModuleState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Version       int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"` // For optimistic concurrency control
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleState) Reset() {
	*x = ModuleState{}
	mi := &file_api_dbos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleState) ProtoMessage() {}

func (x *ModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleState.ProtoReflect.Descriptor instead.
func (*ModuleState) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ModuleState) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModuleState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ModuleState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ModuleState) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ModuleState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ModuleState) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ModuleState) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// MeasurementResult represents a network measurement result
type MeasurementResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId             string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModuleName          string                 `protobuf:"bytes,3,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Data                []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded result data
	Timestamp           int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReceivedAt          int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`                             // When the result was received
	AgentStartTime      int64                  `protobuf:"varint,7,opt,name=agent_start_time,json=agentStartTime,proto3" json:"agent_start_time,omitempty"`               // When the agent started
	AgentRuntimeVersion string                 `protobuf:"bytes,8,opt,name=agent_runtime_version,json=agentRuntimeVersion,proto3" json:"agent_runtime_version,omitempty"` // Agent runtime version
	ModuleRevision      string                 `protobuf:"bytes,9,opt,name=module_revision,json=moduleRevision,proto3" json:"module_revision,omitempty"`                  // Module revision
	DbosServerId        string                 `protobuf:"bytes,10,opt,name=dbos_server_id,json=dbosServerId,proto3" json:"dbos_server_id,omitempty"`                     // DBOS server ID
	IngestSource        string                 `protobuf:"bytes,11,opt,name=ingest_source,json=ingestSource,proto3" json:"ingest_source,omitempty"`                       // Source of the ingestion
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MeasurementResult) Reset() {
	*x = MeasurementResult{}
	mi := &file_api_dbos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementResult) ProtoMessage() {}

func (x *MeasurementResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementResult.ProtoReflect.Descriptor instead.
func (*MeasurementResult) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{2}
}

func (x *MeasurementResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeasurementResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MeasurementResult) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *MeasurementResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MeasurementResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MeasurementResult) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *MeasurementResult) GetAgentStartTime() int64 {
	if x != nil {
		return x.AgentStartTime
	}
	return 0
}

func (x *MeasurementResult) GetAgentRuntimeVersion() string {
	if x != nil {
		return x.AgentRuntimeVersion
	}
	return ""
}

func (x *MeasurementResult) GetModuleRevision() string {
	if x != nil {
		return x.ModuleRevision
	}
	return ""
}

func (x *MeasurementResult) GetDbosServerId() string {
	if x != nil {
		return x.DbosServerId
	}
	return ""
}

func (x *MeasurementResult) GetIngestSource() string {
	if x != nil {
		return x.IngestSource
	}
	return ""
}

// Task represents a scheduled task
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModuleName     string                 `protobuf:"bytes,3,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded task payload
	ScheduledAt    int64                  `protobuf:"varint,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	VisibilityTime int64                  `protobuf:"varint,8,opt,name=visibility_time,json=visibilityTime,proto3" json:"visibility_time,omitempty"` // For visibility timeout
	RetryCount     int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`             // For retry handling
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_dbos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetVisibilityTime() int64 {
	if x != nil {
		return x.VisibilityTime
	}
	return 0
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// Agent Management Requests
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_api_dbos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_api_dbos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_api_dbos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Agent         *Agent                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_api_dbos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *GetAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_dbos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{8}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_dbos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{9}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Module State Requests
type SetModuleStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ModuleState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModuleStateRequest) Reset() {
	*x = SetModuleStateRequest{}
	mi := &file_api_dbos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModuleStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleStateRequest) ProtoMessage() {}

func (x *SetModuleStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleStateRequest.ProtoReflect.Descriptor instead.
func (*SetModuleStateRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{10}
}

func (x *SetModuleStateRequest) GetState() *ModuleState {
	if x != nil {
		return x.State
	}
	return nil
}

type SetModuleStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModuleStateResponse) Reset() {
	*x = SetModuleStateResponse{}
	mi := &file_api_dbos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModuleStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleStateResponse) ProtoMessage() {}

func (x *SetModuleStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleStateResponse.ProtoReflect.Descriptor instead.
func (*SetModuleStateResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{11}
}

func (x *SetModuleStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetModuleStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetModuleStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleStateRequest) Reset() {
	*x = GetModuleStateRequest{}
	mi := &file_api_dbos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleStateRequest) ProtoMessage() {}

func (x *GetModuleStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleStateRequest.ProtoReflect.Descriptor instead.
func (*GetModuleStateRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{12}
}

func (x *GetModuleStateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetModuleStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	State         *ModuleState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleStateResponse) Reset() {
	*x = GetModuleStateResponse{}
	mi := &file_api_dbos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleStateResponse) ProtoMessage() {}

func (x *GetModuleStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleStateResponse.ProtoReflect.Descriptor instead.
func (*GetModuleStateResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{13}
}

func (x *GetModuleStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetModuleStateResponse) GetState() *ModuleState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetModuleStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListModuleStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModuleStatesRequest) Reset() {
	*x = ListModuleStatesRequest{}
	mi := &file_api_dbos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModuleStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleStatesRequest) ProtoMessage() {}

func (x *ListModuleStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleStatesRequest.ProtoReflect.Descriptor instead.
func (*ListModuleStatesRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{14}
}

func (x *ListModuleStatesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListModuleStatesRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

type ListModuleStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*ModuleState         `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModuleStatesResponse) Reset() {
	*x = ListModuleStatesResponse{}
	mi := &file_api_dbos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModuleStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleStatesResponse) ProtoMessage() {}

func (x *ListModuleStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleStatesResponse.ProtoReflect.Descriptor instead.
func (*ListModuleStatesResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{15}
}

func (x *ListModuleStatesResponse) GetStates() []*ModuleState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListModuleStatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Measurement Result Requests
type StoreResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MeasurementResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResultRequest) Reset() {
	*x = StoreResultRequest{}
	mi := &file_api_dbos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResultRequest) ProtoMessage() {}

func (x *StoreResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResultRequest.ProtoReflect.Descriptor instead.
func (*StoreResultRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{16}
}

func (x *StoreResultRequest) GetResult() *MeasurementResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type StoreResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResultResponse) Reset() {
	*x = StoreResultResponse{}
	mi := &file_api_dbos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResultResponse) ProtoMessage() {}

func (x *StoreResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResultResponse.ProtoReflect.Descriptor instead.
func (*StoreResultResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{17}
}

func (x *StoreResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_api_dbos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{18}
}

func (x *GetResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Result        *MeasurementResult     `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultResponse) Reset() {
	*x = GetResultResponse{}
	mi := &file_api_dbos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultResponse) ProtoMessage() {}

func (x *GetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultResponse.ProtoReflect.Descriptor instead.
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{19}
}

func (x *GetResultResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResultResponse) GetResult() *MeasurementResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsRequest) Reset() {
	*x = ListResultsRequest{}
	mi := &file_api_dbos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsRequest) ProtoMessage() {}

func (x *ListResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsRequest.ProtoReflect.Descriptor instead.
func (*ListResultsRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{20}
}

func (x *ListResultsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MeasurementResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsResponse) Reset() {
	*x = ListResultsResponse{}
	mi := &file_api_dbos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsResponse) ProtoMessage() {}

func (x *ListResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsResponse.ProtoReflect.Descriptor instead.
func (*ListResultsResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{21}
}

func (x *ListResultsResponse) GetResults() []*MeasurementResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListResultsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Task Scheduling Requests
type ScheduleTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	mi := &file_api_dbos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{22}
}

func (x *ScheduleTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ScheduleTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskResponse) Reset() {
	*x = ScheduleTaskResponse{}
	mi := &file_api_dbos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskResponse) ProtoMessage() {}

func (x *ScheduleTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{23}
}

func (x *ScheduleTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_dbos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{24}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_dbos_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{25}
}

func (x *GetTaskResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListDueTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueTasksRequest) Reset() {
	*x = ListDueTasksRequest{}
	mi := &file_api_dbos_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueTasksRequest) ProtoMessage() {}

func (x *ListDueTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueTasksRequest.ProtoReflect.Descriptor instead.
func (*ListDueTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{26}
}

func (x *ListDueTasksRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ListDueTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueTasksResponse) Reset() {
	*x = ListDueTasksResponse{}
	mi := &file_api_dbos_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueTasksResponse) ProtoMessage() {}

func (x *ListDueTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueTasksResponse.ProtoReflect.Descriptor instead.
func (*ListDueTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{27}
}

func (x *ListDueTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListDueTasksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AckTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckTaskRequest) Reset() {
	*x = AckTaskRequest{}
	mi := &file_api_dbos_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTaskRequest) ProtoMessage() {}

func (x *AckTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTaskRequest.ProtoReflect.Descriptor instead.
func (*AckTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{28}
}

func (x *AckTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AckTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckTaskResponse) Reset() {
	*x = AckTaskResponse{}
	mi := &file_api_dbos_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTaskResponse) ProtoMessage() {}

func (x *AckTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTaskResponse.ProtoReflect.Descriptor instead.
func (*AckTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{29}
}

func (x *AckTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NackTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RetryDelaySeconds int64                  `protobuf:"varint,2,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NackTaskRequest) Reset() {
	*x = NackTaskRequest{}
	mi := &file_api_dbos_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackTaskRequest) ProtoMessage() {}

func (x *NackTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackTaskRequest.ProtoReflect.Descriptor instead.
func (*NackTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{30}
}

func (x *NackTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NackTaskRequest) GetRetryDelaySeconds() int64 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

type NackTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackTaskResponse) Reset() {
	*x = NackTaskResponse{}
	mi := &file_api_dbos_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackTaskResponse) ProtoMessage() {}

func (x *NackTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackTaskResponse.ProtoReflect.Descriptor instead.
func (*NackTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{31}
}

func (x *NackTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NackTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Event Logging Requests
type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_api_dbos_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{32}
}

func (x *GetEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        [][]byte               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_api_dbos_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dbos_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_dbos_proto_rawDescGZIP(), []int{33}
}

func (x *GetEventsResponse) GetEvents() [][]byte {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_dbos_proto protoreflect.FileDescriptor

const file_api_dbos_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/dbos.proto\x12\x04dbos\"\x9c\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\x03R\tfirstSeen\x12/\n" +
	"\x06config\x18\x06 \x03(\v2\x17.dbos.Agent.ConfigEntryR\x06config\x12)\n" +
	"\x10total_heartbeats\x18\a \x01(\x05R\x0ftotalHeartbeats\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x02\n" +
	"\vModuleState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x128\n" +
	"\adetails\x18\x05 \x03(\v2\x1e.dbos.ModuleState.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x03\n" +
	"\x11MeasurementResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmodule_name\x18\x03 \x01(\tR\n" +
	"moduleName\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\x12(\n" +
	"\x10agent_start_time\x18\a \x01(\x03R\x0eagentStartTime\x122\n" +
	"\x15agent_runtime_version\x18\b \x01(\tR\x13agentRuntimeVersion\x12'\n" +
	"\x0fmodule_revision\x18\t \x01(\tR\x0emoduleRevision\x12$\n" +
	"\x0edbos_server_id\x18\n" +
	" \x01(\tR\fdbosServerId\x12#\n" +
	"\ringest_source\x18\v \x01(\tR\fingestSource\"\x90\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmodule_name\x18\x03 \x01(\tR\n" +
	"moduleName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\x03R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0fvisibility_time\x18\b \x01(\x03R\x0evisibilityTime\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\"9\n" +
	"\x14RegisterAgentRequest\x12!\n" +
	"\x05agent\x18\x01 \x01(\v2\v.dbos.AgentR\x05agent\"G\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"a\n" +
	"\x10GetAgentResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\x05agent\x18\x02 \x01(\v2\v.dbos.AgentR\x05agent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x13\n" +
	"\x11ListAgentsRequest\"O\n" +
	"\x12ListAgentsResponse\x12#\n" +
	"\x06agents\x18\x01 \x03(\v2\v.dbos.AgentR\x06agents\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x15SetModuleStateRequest\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.dbos.ModuleStateR\x05state\"H\n" +
	"\x16SetModuleStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x15GetModuleStateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"m\n" +
	"\x16GetModuleStateResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x05state\x18\x02 \x01(\v2\x11.dbos.ModuleStateR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"U\n" +
	"\x17ListModuleStatesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\"[\n" +
	"\x18ListModuleStatesResponse\x12)\n" +
	"\x06states\x18\x01 \x03(\v2\x11.dbos.ModuleStateR\x06states\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x12StoreResultRequest\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.dbos.MeasurementResultR\x06result\"E\n" +
	"\x13StoreResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x10GetResultRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"p\n" +
	"\x11GetResultResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.dbos.MeasurementResultR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"/\n" +
	"\x12ListResultsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"^\n" +
	"\x13ListResultsResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.dbos.MeasurementResultR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x13ScheduleTaskRequest\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".dbos.TaskR\x04task\"F\n" +
	"\x14ScheduleTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"]\n" +
	"\x0fGetTaskResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1e\n" +
	"\x04task\x18\x02 \x01(\v2\n" +
	".dbos.TaskR\x04task\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"3\n" +
	"\x13ListDueTasksRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"N\n" +
	"\x14ListDueTasksResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".dbos.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x0eAckTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"A\n" +
	"\x0fAckTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Z\n" +
	"\x0fNackTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12.\n" +
	"\x13retry_delay_seconds\x18\x02 \x01(\x03R\x11retryDelaySeconds\"B\n" +
	"\x10NackTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10GetEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"A\n" +
	"\x11GetEventsResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\fR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf6\a\n" +
	"\x04DBOS\x12H\n" +
	"\rRegisterAgent\x12\x1a.dbos.RegisterAgentRequest\x1a\x1b.dbos.RegisterAgentResponse\x129\n" +
	"\bGetAgent\x12\x15.dbos.GetAgentRequest\x1a\x16.dbos.GetAgentResponse\x12?\n" +
	"\n" +
	"ListAgents\x12\x17.dbos.ListAgentsRequest\x1a\x18.dbos.ListAgentsResponse\x12K\n" +
	"\x0eSetModuleState\x12\x1b.dbos.SetModuleStateRequest\x1a\x1c.dbos.SetModuleStateResponse\x12K\n" +
	"\x0eGetModuleState\x12\x1b.dbos.GetModuleStateRequest\x1a\x1c.dbos.GetModuleStateResponse\x12Q\n" +
	"\x10ListModuleStates\x12\x1d.dbos.ListModuleStatesRequest\x1a\x1e.dbos.ListModuleStatesResponse\x12B\n" +
	"\vStoreResult\x12\x18.dbos.StoreResultRequest\x1a\x19.dbos.StoreResultResponse\x12<\n" +
	"\tGetResult\x12\x16.dbos.GetResultRequest\x1a\x17.dbos.GetResultResponse\x12B\n" +
	"\vListResults\x12\x18.dbos.ListResultsRequest\x1a\x19.dbos.ListResultsResponse\x12E\n" +
	"\fScheduleTask\x12\x19.dbos.ScheduleTaskRequest\x1a\x1a.dbos.ScheduleTaskResponse\x126\n" +
	"\aGetTask\x12\x14.dbos.GetTaskRequest\x1a\x15.dbos.GetTaskResponse\x12E\n" +
	"\fListDueTasks\x12\x19.dbos.ListDueTasksRequest\x1a\x1a.dbos.ListDueTasksResponse\x126\n" +
	"\aAckTask\x12\x14.dbos.AckTaskRequest\x1a\x15.dbos.AckTaskResponse\x129\n" +
	"\bNackTask\x12\x15.dbos.NackTaskRequest\x1a\x16.dbos.NackTaskResponse\x12<\n" +
	"\tGetEvents\x12\x16.dbos.GetEventsRequest\x1a\x17.dbos.GetEventsResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_dbos_proto_rawDescOnce sync.Once
	file_api_dbos_proto_rawDescData []byte
)

func file_api_dbos_proto_rawDescGZIP() []byte {
	file_api_dbos_proto_rawDescOnce.Do(func() {
		file_api_dbos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dbos_proto_rawDesc), len(file_api_dbos_proto_rawDesc)))
	})
	return file_api_dbos_proto_rawDescData
}

var file_api_dbos_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_dbos_proto_goTypes = []any{
	(*Agent)(nil),                    // 0: dbos.Agent
	(*ModuleState)(nil),              // 1: dbos.ModuleState
	(*MeasurementResult)(nil),        // 2: dbos.MeasurementResult
	(*Task)(nil),                     // 3: dbos.Task
	(*RegisterAgentRequest)(nil),     // 4: dbos.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),    // 5: dbos.RegisterAgentResponse
	(*GetAgentRequest)(nil),          // 6: dbos.GetAgentRequest
	(*GetAgentResponse)(nil),         // 7: dbos.GetAgentResponse
	(*ListAgentsRequest)(nil),        // 8: dbos.ListAgentsRequest
	(*ListAgentsResponse)(nil),       // 9: dbos.ListAgentsResponse
	(*SetModuleStateRequest)(nil),    // 10: dbos.SetModuleStateRequest
	(*SetModuleStateResponse)(nil),   // 11: dbos.SetModuleStateResponse
	(*GetModuleStateRequest)(nil),    // 12: dbos.GetModuleStateRequest
	(*GetModuleStateResponse)(nil),   // 13: dbos.GetModuleStateResponse
	(*ListModuleStatesRequest)(nil),  // 14: dbos.ListModuleStatesRequest
	(*ListModuleStatesResponse)(nil), // 15: dbos.ListModuleStatesResponse
	(*StoreResultRequest)(nil),       // 16: dbos.StoreResultRequest
	(*StoreResultResponse)(nil),      // 17: dbos.StoreResultResponse
	(*GetResultRequest)(nil),         // 18: dbos.GetResultRequest
	(*GetResultResponse)(nil),        // 19: dbos.GetResultResponse
	(*ListResultsRequest)(nil),       // 20: dbos.ListResultsRequest
	(*ListResultsResponse)(nil),      // 21: dbos.ListResultsResponse
	(*ScheduleTaskRequest)(nil),      // 22: dbos.ScheduleTaskRequest
	(*ScheduleTaskResponse)(nil),     // 23: dbos.ScheduleTaskResponse
	(*GetTaskRequest)(nil),           // 24: dbos.GetTaskRequest
	(*GetTaskResponse)(nil),          // 25: dbos.GetTaskResponse
	(*ListDueTasksRequest)(nil),      // 26: dbos.ListDueTasksRequest
	(*ListDueTasksResponse)(nil),     // 27: dbos.ListDueTasksResponse
	(*AckTaskRequest)(nil),           // 28: dbos.AckTaskRequest
	(*AckTaskResponse)(nil),          // 29: dbos.AckTaskResponse
	(*NackTaskRequest)(nil),          // 30: dbos.NackTaskRequest
	(*NackTaskResponse)(nil),         // 31: dbos.NackTaskResponse
	(*GetEventsRequest)(nil),         // 32: dbos.GetEventsRequest
	(*GetEventsResponse)(nil),        // 33: dbos.GetEventsResponse
	nil,                              // 34: dbos.Agent.ConfigEntry
	nil,                              // 35: dbos.ModuleState.DetailsEntry
}
var file_api_dbos_proto_depIdxs = []int32{
	34, // 0: dbos.Agent.config:type_name -> dbos.Agent.ConfigEntry
	35, // 1: dbos.ModuleState.details:type_name -> dbos.ModuleState.DetailsEntry
	0,  // 2: dbos.RegisterAgentRequest.agent:type_name -> dbos.Agent
	0,  // 3: dbos.GetAgentResponse.agent:type_name -> dbos.Agent
	0,  // 4: dbos.ListAgentsResponse.agents:type_name -> dbos.Agent
	1,  // 5: dbos.SetModuleStateRequest.state:type_name -> dbos.ModuleState
	1,  // 6: dbos.GetModuleStateResponse.state:type_name -> dbos.ModuleState
	1,  // 7: dbos.ListModuleStatesResponse.states:type_name -> dbos.ModuleState
	2,  // 8: dbos.StoreResultRequest.result:type_name -> dbos.MeasurementResult
	2,  // 9: dbos.GetResultResponse.result:type_name -> dbos.MeasurementResult
	2,  // 10: dbos.ListResultsResponse.results:type_name -> dbos.MeasurementResult
	3,  // 11: dbos.ScheduleTaskRequest.task:type_name -> dbos.Task
	3,  // 12: dbos.GetTaskResponse.task:type_name -> dbos.Task
	3,  // 13: dbos.ListDueTasksResponse.tasks:type_name -> dbos.Task
	4,  // 14: dbos.DBOS.RegisterAgent:input_type -> dbos.RegisterAgentRequest
	6,  // 15: dbos.DBOS.GetAgent:input_type -> dbos.GetAgentRequest
	8,  // 16: dbos.DBOS.ListAgents:input_type -> dbos.ListAgentsRequest
	10, // 17: dbos.DBOS.SetModuleState:input_type -> dbos.SetModuleStateRequest
	12, // 18: dbos.DBOS.GetModuleState:input_type -> dbos.GetModuleStateRequest
	14, // 19: dbos.DBOS.ListModuleStates:input_type -> dbos.ListModuleStatesRequest
	16, // 20: dbos.DBOS.StoreResult:input_type -> dbos.StoreResultRequest
	18, // 21: dbos.DBOS.GetResult:input_type -> dbos.GetResultRequest
	20, // 22: dbos.DBOS.ListResults:input_type -> dbos.ListResultsRequest
	22, // 23: dbos.DBOS.ScheduleTask:input_type -> dbos.ScheduleTaskRequest
	24, // 24: dbos.DBOS.GetTask:input_type -> dbos.GetTaskRequest
	26, // 25: dbos.DBOS.ListDueTasks:input_type -> dbos.ListDueTasksRequest
	28, // 26: dbos.DBOS.AckTask:input_type -> dbos.AckTaskRequest
	30, // 27: dbos.DBOS.NackTask:input_type -> dbos.NackTaskRequest
	32, // 28: dbos.DBOS.GetEvents:input_type -> dbos.GetEventsRequest
	5,  // 29: dbos.DBOS.RegisterAgent:output_type -> dbos.RegisterAgentResponse
	7,  // 30: dbos.DBOS.GetAgent:output_type -> dbos.GetAgentResponse
	9,  // 31: dbos.DBOS.ListAgents:output_type -> dbos.ListAgentsResponse
	11, // 32: dbos.DBOS.SetModuleState:output_type -> dbos.SetModuleStateResponse
	13, // 33: dbos.DBOS.GetModuleState:output_type -> dbos.GetModuleStateResponse
	15, // 34: dbos.DBOS.ListModuleStates:output_type -> dbos.ListModuleStatesResponse
	17, // 35: dbos.DBOS.StoreResult:output_type -> dbos.StoreResultResponse
	19, // 36: dbos.DBOS.GetResult:output_type -> dbos.GetResultResponse
	21, // 37: dbos.DBOS.ListResults:output_type -> dbos.ListResultsResponse
	23, // 38: dbos.DBOS.ScheduleTask:output_type -> dbos.ScheduleTaskResponse
	25, // 39: dbos.DBOS.GetTask:output_type -> dbos.GetTaskResponse
	27, // 40: dbos.DBOS.ListDueTasks:output_type -> dbos.ListDueTasksResponse
	29, // 41: dbos.DBOS.AckTask:output_type -> dbos.AckTaskResponse
	31, // 42: dbos.DBOS.NackTask:output_type -> dbos.NackTaskResponse
	33, // 43: dbos.DBOS.GetEvents:output_type -> dbos.GetEventsResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_dbos_proto_init() }
func file_api_dbos_proto_init() {
	if File_api_dbos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dbos_proto_rawDesc), len(file_api_dbos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dbos_proto_goTypes,
		DependencyIndexes: file_api_dbos_proto_depIdxs,
		MessageInfos:      file_api_dbos_proto_msgTypes,
	}.Build()
	File_api_dbos_proto = out.File
	file_api_dbos_proto_goTypes = nil
	file_api_dbos_proto_depIdxs = nil
}
